name: Snowflake CICD Full Refresh

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from UI

concurrency:
  # Ensure only one instance of this workflow runs across all PRs to prevent database conflicts
  group: ci-testing
  # Don't cancel in-progress runs automatically
  cancel-in-progress: false

env:
  # 1. Define where your dbt project lives relative to the repo root
  # If dbt is in the root, leave this as "."
  # If dbt is in a subfolder, change to "./my_dbt_folder"
  DBT_PROJECT_DIR: "." 

jobs:
  dbt_run:
    name: dbt full refresh and test on Snowflake
    runs-on: ubuntu-latest

    # Set the environment variables dbt needs to connect
    env:
      DBT_SNOWFLAKE_DEV_ACCOUNT: ${{ secrets.DBT_TUVA_SNOWFLAKE_ACCOUNT }}
      DBT_SNOWFLAKE_DEV_CI_DATABASE: ${{ secrets.DBT_TUVA_CI_DATABASE }}
      DBT_SNOWFLAKE_DEV_CI_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_CI_PASSWORD }}  
      DBT_SNOWFLAKE_DEV_CI_ROLE: ${{ secrets.DBT_SNOWFLAKE_CI_ROLE }}
      DBT_SNOWFLAKE_DEV_CI_SCHEMA: ${{ secrets.DBT_SNOWFLAKE_CI_SCHEMA }}
      DBT_SNOWFLAKE_DEV_CI_USER: ${{ secrets.DBT_SNOWFLAKE_CI_USER }}
      DBT_SNOWFLAKE_DEV_CI_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_CI_WAREHOUSE }}

    steps:
      # 1. Checkout the code (Crucial step!)
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      # 3. Quick check that secrets are available 
      - name: Debug Secrets
        env:
          MY_HOST: ${{ secrets.DBT_TUVA_SNOWFLAKE_ACCOUNT }}
        run: |
          if [ -z "$MY_HOST" ]; then
            echo "❌ Error: DBT_TUVA_SNOWFLAKE_ACCOUNT is empty!"
          else
            echo "✅ Success: DBT_TUVA_SNOWFLAKE_ACCOUNT is found (Length: ${#MY_HOST})"
          fi

      # 3. Install dbt-redshift
      - name: Install dbt
        run: pip install dbt-snowflake

      # 4. Install dbt dependencies (if you have packages.yml)
      - name: Install dbt dependencies
        working-directory: ${{ env.DBT_PROJECT_DIR }}
        run: dbt deps --profiles-dir ./integration_tests/profiles/snowflake

      # 5. Debug Connection (Optional but recommended)
      # This checks if profiles.yml can connect to Redshift
      - name: Test Connection
        working-directory: ${{ env.DBT_PROJECT_DIR }}
        run: dbt debug --profiles-dir ./integration_tests/profiles/snowflake

      # 6. Run dbt models
      - name: Run build models
        working-directory: ${{ env.DBT_PROJECT_DIR }}
        run: dbt build --full-refresh --profiles-dir ./integration_tests/profiles/snowflake