name: BigQuery CICD Full Refresh
# on:
#   pull_request:
#     branches:
#       - main
#   workflow_dispatch: # Allows manual trigger from UI

jobs:
  dbt_run:
    name: dbt full refresh and test on BigQuery
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.10"
      DBT_PROJECT_DIR: "."
      DBT_CORE_VERSION: "1.10.15"

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dbt-core and BigQuery adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==${{ DBT_CORE_VERISON }} dbt-bigquery

      - name: Create dbt profiles.yml for BigQuery
        run: |
          mkdir -p ./integration_tests/profiles/bigquery
          echo "default:
            outputs:
              dev:
                type: bigquery
                method: service-account
                project: dev-ci-testing
                keyfile: ./creds.json
                dataset: connector
                threads: 8
                timeout_seconds: 300
                priority: interactive
            target: dev" > ./integration_tests/profiles/bigquery/profiles.yml
        working-directory: ${{ env.DBT_PROJECT_DIR }}

      - name: Create BigQuery credentials file
        run: |
          echo "${{ secrets.TUVA_BIGQUERY_TOKEN }}" | base64 --decode > ./creds.json
        working-directory: ${{ env.DBT_PROJECT_DIR }}

      - name: Install dbt dependencies
        run: dbt deps --profiles-dir ./integration_tests/profiles/bigquery
        working-directory: ${{ env.DBT_PROJECT_DIR }}

      - name: Test Connection
        run: dbt debug --profiles-dir ./integration_tests/profiles/bigquery
        working-directory: ${{ env.DBT_PROJECT_DIR }}

      - name: Build dbt models (full-refresh)
        run: |
          dbt build --full-refresh --profiles-dir ./integration_tests/profiles/bigquery
        working-directory: ${{ env.DBT_PROJECT_DIR }}

      - name: Get the result
        if: ${{ always() }}
        run: echo "${{ steps.dbt-build.outputs.result }}"
        shell: bash